apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop-website
  labels:
    tier: static-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coffee-shop-website
  template:
    metadata:
      labels:
        app: coffee-shop-website
        tier: static-webpage
    spec:
      containers:
      - name: coffee-shop-website
        image: your-company-name/coffee-shop-web:v2
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
